import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from matplotlib.ticker import MultipleLocator, AutoLocator, FixedLocator

ti = (11.0, 11.25, 11.5, 11.75, 12.0)
tex = ('00:00', '06:00', '12:00', '18:00', '24:00')
distance = (1, 2, 3, 4)
# dis = ('1', '2', '3', '4', '5', '6')

scatter_size = 50
xray = "Local Time"
ps = 20

data = np.loadtxt("build/2_zy_out.txt")
data = np.array(data)
x = data[:, 0]
y = data[:, 1]
TABC = data[:, 2]
PDR = data[:, 4]
CR = data[:, 5]
extinction = data[:, 3]
vol = data[:, 6]
Re = data[:, 7]


fig = plt.figure(figsize = (30,25))
plt.suptitle('Lidar measurements in Zhangye (38.9$^\circ$N,100.5$^\circ$E)', size = 40)
plt.subplot(321)
plt.title('2023-02-11',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
plt.xticks([])
ax.xaxis.set_minor_locator(xminor)
# ax.set_xticks(ti)
# ax.set_xticklabels(tex)
ax.tick_params(axis='x',labelbottom=False)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Atten. backs. coef. (532nm)',size=35,color='r')
plt.scatter(x,y,c = TABC, vmin = 0, vmax = 0.005, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
cb.ax.set_title('(/sr/km)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# ax.remove()
# plt.tight_layout()

plt.subplot(322)
plt.title('2023-02-11',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
plt.xticks([])
ax.xaxis.set_minor_locator(xminor)
ax.tick_params(axis='x',labelbottom=False)
# ax.set_xticks(ti)
# ax.set_xticklabels(tex)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Extinction coefficient (532nm)',size=35,color='r')
plt.scatter(x,y,c = extinction, vmin = 0, vmax = 0.2, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
cb.ax.set_title('(/km)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# ax.remove()
# plt.tight_layout()

plt.subplot(323)
# plt.title('2023-02-07',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
plt.xticks([])
ax.xaxis.set_minor_locator(xminor)
ax.tick_params(axis='x',labelbottom=False)
# ax.set_xticks(ti)
# ax.set_xticklabels(tex)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Color ratio (1064 nm/532nm)',size=35,color='r')
plt.scatter(x,y,c = CR, vmin = 0, vmax = 1, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
# cb.ax.set_title('(/km)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# ax.remove()
# plt.tight_layout()

plt.subplot(324)
# plt.title('2023-02-07',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
plt.xticks([])
ax.xaxis.set_minor_locator(xminor)
ax.tick_params(axis='x',labelbottom=False)
# ax.set_xticks(ti)
# ax.set_xticklabels(tex)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Depolarization ratio (532nm)',size=35,color='r')
plt.scatter(x,y,c = PDR, vmin = 0, vmax = 0.4, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
# cb.ax.set_title('(/km)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# ax.remove()
# plt.tight_layout()

plt.subplot(325)
# plt.title('2023-02-07',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
ax.xaxis.set_minor_locator(xminor)
ax.set_xticks(ti)
ax.set_xticklabels(tex)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Vol. conc.',size=35,color='r')
plt.scatter(x,y,c = vol, vmin = 0, vmax = 1.0, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
plt.xlabel(xray,size=35)
cb.ax.set_title('($\u03BCm^3$/$\u03BCm^2$)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# ax.remove()
# plt.tight_layout()

plt.subplot(326)
# plt.title('2023-02-07',size=35)
plt.xlim([11, 12])
plt.ylim([0.2,4.5])
ax=plt.gca()
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
ax.spines['top'].set_linewidth(3)
xminor=MultipleLocator(1.0 / 24.0)
xmajor_locator = MultipleLocator(0.25)
ax.xaxis.set_major_locator(xmajor_locator)
ax.xaxis.set_minor_locator(xminor)
ax.set_xticks(ti)
ax.set_xticklabels(tex)
plt.yticks(distance)
plt.tick_params(which="major",width = 3,length=10)
plt.tick_params(which="minor",width = 3,length=5)
plt.text(11.02,4,'Eff. radius',size=35,color='r')
plt.scatter(x,y,c = Re, vmin = 0, vmax = 2, s = scatter_size, cmap = plt.get_cmap("jet"))
cb=plt.colorbar()
plt.xlabel(xray,size=35)
cb.ax.set_title('(\u03BCm)',size=30, pad = 15)
cb.ax.tick_params(labeltop = True, labelsize = ps)
plt.tick_params(labelsize=30)
plt.ylabel('Height (km)',size=35)
# plt.tight_layout()
plt.subplots_adjust(hspace = 0.15, wspace = 0.03)
plt.subplots_adjust(left=0.05,bottom=0.085,right=1.0,top=0.87)
plt.savefig("zy_02.png")







